
# ============================================================
# 19. Smoke/full gate and machine-readable summary
# ============================================================
fullrow=ABLATION_SUMMARY[ABLATION_SUMMARY.ablation=="FULL"].iloc[0].to_dict() if len(ABLATION_SUMMARY) else {}
if RUN_PROFILE=="full":
    targets={"exact_permission_accuracy":bool(fullrow.get("exact_permission_accuracy_estimate",np.nan)>=SUCCESS_CRITERIA["exact_permission_accuracy_min"]),"false_admission_rate":bool(fullrow.get("false_admission_rate_estimate",np.inf)<=SUCCESS_CRITERIA["false_admission_rate_max"]),"false_rejection_rate":bool(fullrow.get("false_rejection_rate_estimate",np.inf)<=SUCCESS_CRITERIA["false_rejection_rate_max"]),"mixed_failure_precedence_accuracy":bool(fullrow.get("mixed_failure_precedence_accuracy_estimate",np.nan)>=SUCCESS_CRITERIA["mixed_failure_precedence_accuracy_min"])}
else: targets={}
SUMMARY={"experiment_version":EXPERIMENT_VERSION,"run_profile":RUN_PROFILE,"protocol_hash":PROTOCOL_HASH,"canonical_notebook_sha256":CANONICAL_SHA256,"canonical_definition_count":len(DEFINITION_AUDIT),"canonical_p0_decision_sha256":CANONICAL_P0_DECISION_SHA256,"active_scenarios":ACTIVE_SCENARIO_IDS,"active_fixture_replicates":ACTIVE_FIXTURE_REPLICATES,"active_protocol_seeds":ACTIVE_PROTOCOL_SEEDS,"active_models":ACTIVE_MODEL_IDS,"core_result_units":len(CORE_RESULTS_FRAME),"expected_core_result_units":expected_units,"utility_execution_error_rows":len(UTILITY_EXECUTION_ERRORS),"all_jobs_completed_without_exception":bool(len(CORE_RESULTS_FRAME)==expected_units and len(UTILITY_EXECUTION_ERRORS)==0),"structural_precedence_passed":bool(STRUCTURAL_PRECEDENCE.correct.all()),"full_stack_operating_characteristics":fullrow,"engineering_success_criteria":SUCCESS_CRITERIA,"engineering_target_results":targets,"engineering_targets_all_passed":bool(targets and all(targets.values())) if RUN_PROFILE=="full" else None,"misclassified_units":len(FAILURES),"severity_rows":len(SEVERITY_RESULTS),"cache_stats":CACHE_STATS,"elapsed_hours":(time.time()-PROJECT_START)/3600,"scientific_interpretation_allowed":RUN_PROFILE=="full","stage3a_rule":"reference_skill_gain crossed pair-seed 95% CI lower bound > 0","scope_warning":"Controlled post-hoc benchmark only; not population validity or untouched residential confirmation."}
name="KNOWN_TRUTH_VALIDATION_SUMMARY.json" if RUN_PROFILE=="full" else "SMOKE_GATE.json"; write_json(PROFILE_ROOT/name,SUMMARY); write_json(OUTPUT_ROOT/(RUN_PROFILE+"_"+name),SUMMARY); print(json.dumps(normalise_json(SUMMARY),indent=2))
if RUN_PROFILE=="smoke": print("\nSMOKE COMPLETE. Inspect SMOKE_GATE.json; then switch RUN_PROFILE to full, restart and Run All.")
else: print("\nFULL CAMPAIGN COMPLETE. Return the executed notebook/HTML and complete output directory.")
